/*
 * Vystia Class System v2.0
 * Ability Definition Framework
 *
 * This file defines the data-driven ability structure.
 * Abilities are defined as data that can be generated by Python automation.
 */

using System;
using System.Collections.Generic;
using Server;
using Server.Custom.VystiaClasses.Systems;

namespace Server.Custom.VystiaClasses.Abilities
{
    #region Enums

    /// <summary>
    /// Target type for abilities
    /// </summary>
    public enum AbilityTargetType
    {
        Self,               // Affects caster only
        SingleTarget,       // Requires targeting an enemy
        SingleFriendly,     // Requires targeting an ally
        GroundTarget,       // Target a location
        Cone,               // Cone in front of caster
        Line,               // Line from caster
        PointBlankAoE,      // AoE centered on caster
        TargetAoE,          // AoE centered on target
        ChainTarget,        // Bounces between targets
        Passive             // Always active, no activation
    }

    /// <summary>
    /// Type of ability effect
    /// </summary>
    public enum AbilityEffectType
    {
        // Damage
        DirectDamage,
        DamageOverTime,
        PercentDamage,          // % of target's HP

        // Healing
        DirectHeal,
        HealOverTime,
        PercentHeal,            // % of target's HP
        Absorb,                 // Damage shield

        // Buffs/Debuffs
        ApplyBuff,
        ApplyDebuff,
        RemoveBuff,
        RemoveDebuff,
        DispelMagic,

        // Crowd Control
        ApplyCC,
        RemoveCC,

        // Resource
        RestoreMana,
        RestoreStamina,
        DrainMana,
        DrainStamina,
        GenerateResource,       // Secondary resource
        ConsumeResource,        // Secondary resource

        // Stacks
        ApplyStack,
        ConsumeStack,
        CheckStack,             // Conditional based on stacks

        // Summon
        Summon,
        Dismiss,
        PetCommand,

        // Transform
        ApplyTransform,
        RemoveTransform,

        // Movement
        Teleport,
        Knockback,
        Pull,
        Leap,

        // Utility
        BreakStealth,
        EnterStealth,
        Interrupt,
        Taunt,
        ThreatModify,

        // Special
        ConditionalEffect,      // If X then Y
        RepeatEffect,           // Repeat X times
        DelayedEffect,          // Trigger after delay
        TriggerAbility          // Cast another ability
    }

    /// <summary>
    /// Weapon type requirements
    /// </summary>
    public enum WeaponRequirement
    {
        None,
        Any,
        Sword,
        Axe,
        Mace,
        Polearm,
        Staff,
        Dagger,
        Bow,
        Crossbow,
        Throwing,
        Fist,
        Shield,
        TwoHanded,
        DualWield
    }

    /// <summary>
    /// Magic school for the ability
    /// </summary>
    public enum AbilitySchool
    {
        // Magic Schools
        Ice,
        Nature,
        Hex,
        Elemental,
        Dark,
        Divination,
        Necromancy,
        Summoning,
        Shamanic,
        Bardic,
        Enchanting,
        Illusion,

        // Martial Schools
        Fighter,
        Barbarian,
        Monk,
        Rogue,
        Ranger,
        Knight,
        Paladin,
        Templar,
        BountyHunter,
        Beastmaster,
        Artificer,
        Alchemist,
        Cleric,
        Wizard
    }

    #endregion

    #region Effect Definition

    /// <summary>
    /// Defines a single effect within an ability
    /// </summary>
    public class AbilityEffect
    {
        public AbilityEffectType Type { get; set; }

        // Damage/Heal values
        public int MinValue { get; set; }
        public int MaxValue { get; set; }
        public VystiaDamageType DamageType { get; set; }

        // Duration for DoTs/HoTs/Buffs
        public TimeSpan Duration { get; set; }

        // Stacks
        public StackType StackType { get; set; }
        public int StackCount { get; set; }

        // Buff type
        public VystiaBuffType BuffType { get; set; }

        // CC type
        public CCType CCType { get; set; }

        // Resource type
        public ResourceType ResourceType { get; set; }
        public int ResourceAmount { get; set; }

        // Summon type (class name)
        public string SummonType { get; set; }
        public int SummonDuration { get; set; }

        // Transform body ID
        public int TransformBody { get; set; }
        public int TransformHue { get; set; }

        // Knockback/Pull distance
        public int Distance { get; set; }

        // Conditional bonuses
        public string Condition { get; set; }           // e.g., "TargetFrozen", "TargetBelow20Percent"
        public double ConditionalMultiplier { get; set; }
        public AbilityEffect ConditionalEffect { get; set; }

        // Repeat/Chain
        public int RepeatCount { get; set; }
        public int ChainTargets { get; set; }
        public double ChainFalloff { get; set; }        // Damage reduction per bounce

        // Delayed effect
        public TimeSpan Delay { get; set; }

        // Trigger another ability
        public int TriggeredAbilityId { get; set; }
        public double TriggerChance { get; set; }

        // Visual/Sound
        public int EffectId { get; set; }
        public int EffectHue { get; set; }
        public int SoundId { get; set; }

        public AbilityEffect()
        {
            DamageType = VystiaDamageType.Physical;
            Duration = TimeSpan.Zero;
            StackCount = 1;
            ConditionalMultiplier = 1.0;
            TriggerChance = 1.0;
            ChainFalloff = 0.25;
        }

        public AbilityEffect Clone()
        {
            return (AbilityEffect)this.MemberwiseClone();
        }
    }

    #endregion

    #region Ability Definition

    /// <summary>
    /// Complete definition of an ability
    /// </summary>
    public class AbilityDefinition
    {
        #region Identity

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public AbilitySchool School { get; set; }
        public int Circle { get; set; }                  // 1-8 for spells, 1-4 for martial

        #endregion

        #region Costs

        public int ManaCost { get; set; }
        public int StaminaCost { get; set; }
        public int HealthCost { get; set; }             // Life tap style
        public Dictionary<ResourceType, int> SecondaryCosts { get; set; }
        public int ReagentCost { get; set; }            // Generic reagent count

        #endregion

        #region Targeting

        public AbilityTargetType TargetType { get; set; }
        public int Range { get; set; }                  // Tiles
        public int AoERadius { get; set; }              // For AoE abilities
        public int ConeAngle { get; set; }              // Degrees for cone
        public int MaxTargets { get; set; }             // Max targets for AoE
        public bool RequiresLineOfSight { get; set; }

        #endregion

        #region Timing

        public TimeSpan CastTime { get; set; }          // Channel time
        public TimeSpan Cooldown { get; set; }
        public string SharedCooldownGroup { get; set; }  // Abilities share cooldown
        public TimeSpan GlobalCooldownOverride { get; set; }  // Custom GCD

        #endregion

        #region Requirements

        public ResourceType? RequiredStance { get; set; }
        public int MinResourceStacks { get; set; }      // e.g., 5 Chi for finisher
        public bool RequiresStealth { get; set; }
        public bool RequiresBehindTarget { get; set; }
        public bool RequiresCombo { get; set; }         // Must follow another ability
        public int[] ComboFromAbilities { get; set; }   // IDs that enable this
        public WeaponRequirement RequiredWeapon { get; set; }
        public int MinLevel { get; set; }
        public int MinSkill { get; set; }               // Skill value required

        #endregion

        #region Effects

        public List<AbilityEffect> Effects { get; set; }

        #endregion

        #region Resource Generation

        public Dictionary<ResourceType, int> ResourceGeneration { get; set; }

        #endregion

        #region Modifiers

        public bool CanCrit { get; set; }
        public double CritChanceBonus { get; set; }
        public double CritMultiplierBonus { get; set; }
        public bool IgnoresArmor { get; set; }
        public bool IgnoresResistance { get; set; }
        public int ArmorPenetration { get; set; }

        #endregion

        #region Visual/Sound

        public int CastAnimation { get; set; }
        public int CastSound { get; set; }
        public int ImpactEffectId { get; set; }
        public int ImpactEffectHue { get; set; }
        public int ImpactSound { get; set; }
        public int ProjectileId { get; set; }           // For ranged abilities
        public int ProjectileHue { get; set; }
        public int ProjectileSpeed { get; set; }

        #endregion

        #region Flags

        public bool IsChanneled { get; set; }
        public bool IsInstant { get; set; }
        public bool BreaksStealth { get; set; }
        public bool CanBeInterrupted { get; set; }
        public bool IgnoresGlobalCooldown { get; set; }
        public bool IsPassive { get; set; }
        public bool ConsumesStacks { get; set; }        // Uses up stacks like combo points
        public bool IsFinisher { get; set; }            // Consumes all stacks for bonus

        #endregion

        #region Constructor

        public AbilityDefinition()
        {
            // Defaults
            Circle = 1;
            Range = 12;
            MaxTargets = 1;
            RequiresLineOfSight = true;
            CanCrit = true;
            CritChanceBonus = 0;
            CritMultiplierBonus = 0;
            BreaksStealth = true;
            CanBeInterrupted = true;
            RequiredWeapon = WeaponRequirement.None;

            SecondaryCosts = new Dictionary<ResourceType, int>();
            Effects = new List<AbilityEffect>();
            ResourceGeneration = new Dictionary<ResourceType, int>();
            ComboFromAbilities = new int[0];
        }

        #endregion

        #region Builder Pattern

        public AbilityDefinition WithId(int id)
        {
            Id = id;
            return this;
        }

        public AbilityDefinition WithName(string name)
        {
            Name = name;
            return this;
        }

        public AbilityDefinition WithDescription(string desc)
        {
            Description = desc;
            return this;
        }

        public AbilityDefinition InSchool(AbilitySchool school)
        {
            School = school;
            return this;
        }

        public AbilityDefinition InCircle(int circle)
        {
            Circle = circle;
            return this;
        }

        public AbilityDefinition WithManaCost(int cost)
        {
            ManaCost = cost;
            return this;
        }

        public AbilityDefinition WithStaminaCost(int cost)
        {
            StaminaCost = cost;
            return this;
        }

        public AbilityDefinition WithSecondaryCost(ResourceType type, int amount)
        {
            SecondaryCosts[type] = amount;
            return this;
        }

        public AbilityDefinition Targeting(AbilityTargetType type, int range = 12)
        {
            TargetType = type;
            Range = range;
            return this;
        }

        public AbilityDefinition WithAoE(int radius, int maxTargets = 10)
        {
            AoERadius = radius;
            MaxTargets = maxTargets;
            return this;
        }

        public AbilityDefinition WithCastTime(double seconds)
        {
            CastTime = TimeSpan.FromSeconds(seconds);
            return this;
        }

        public AbilityDefinition WithCooldown(double seconds)
        {
            Cooldown = TimeSpan.FromSeconds(seconds);
            return this;
        }

        public AbilityDefinition SharesCooldownWith(string group)
        {
            SharedCooldownGroup = group;
            return this;
        }

        public AbilityDefinition RequiresStance(ResourceType stance)
        {
            RequiredStance = stance;
            return this;
        }

        public AbilityDefinition RequiresMinResource(int stacks)
        {
            MinResourceStacks = stacks;
            return this;
        }

        public AbilityDefinition RequiresWeapon(WeaponRequirement weapon)
        {
            RequiredWeapon = weapon;
            return this;
        }

        public AbilityDefinition IsStealthRequired()
        {
            RequiresStealth = true;
            BreaksStealth = true;
            return this;
        }

        public AbilityDefinition AsFinisher()
        {
            IsFinisher = true;
            ConsumesStacks = true;
            return this;
        }

        public AbilityDefinition AsInstant()
        {
            IsInstant = true;
            CastTime = TimeSpan.Zero;
            return this;
        }

        public AbilityDefinition AsChanneled(double seconds)
        {
            IsChanneled = true;
            CastTime = TimeSpan.FromSeconds(seconds);
            return this;
        }

        public AbilityDefinition AsPassive()
        {
            IsPassive = true;
            TargetType = AbilityTargetType.Passive;
            return this;
        }

        public AbilityDefinition WithEffect(AbilityEffect effect)
        {
            Effects.Add(effect);
            return this;
        }

        public AbilityDefinition WithDamage(int min, int max, VystiaDamageType type = VystiaDamageType.Physical)
        {
            Effects.Add(new AbilityEffect
            {
                Type = AbilityEffectType.DirectDamage,
                MinValue = min,
                MaxValue = max,
                DamageType = type
            });
            return this;
        }

        public AbilityDefinition WithHeal(int min, int max)
        {
            Effects.Add(new AbilityEffect
            {
                Type = AbilityEffectType.DirectHeal,
                MinValue = min,
                MaxValue = max
            });
            return this;
        }

        public AbilityDefinition WithDoT(int damage, double durationSeconds, VystiaDamageType type = VystiaDamageType.Physical)
        {
            Effects.Add(new AbilityEffect
            {
                Type = AbilityEffectType.DamageOverTime,
                MinValue = damage,
                MaxValue = damage,
                Duration = TimeSpan.FromSeconds(durationSeconds),
                DamageType = type
            });
            return this;
        }

        public AbilityDefinition WithHoT(int heal, double durationSeconds)
        {
            Effects.Add(new AbilityEffect
            {
                Type = AbilityEffectType.HealOverTime,
                MinValue = heal,
                MaxValue = heal,
                Duration = TimeSpan.FromSeconds(durationSeconds)
            });
            return this;
        }

        public AbilityDefinition WithBuff(VystiaBuffType buff, double durationSeconds, int value = 0)
        {
            Effects.Add(new AbilityEffect
            {
                Type = AbilityEffectType.ApplyBuff,
                BuffType = buff,
                Duration = TimeSpan.FromSeconds(durationSeconds),
                MinValue = value
            });
            return this;
        }

        public AbilityDefinition WithDebuff(VystiaBuffType debuff, double durationSeconds, int value = 0)
        {
            Effects.Add(new AbilityEffect
            {
                Type = AbilityEffectType.ApplyDebuff,
                BuffType = debuff,
                Duration = TimeSpan.FromSeconds(durationSeconds),
                MinValue = value
            });
            return this;
        }

        public AbilityDefinition WithCC(CCType cc, double durationSeconds)
        {
            Effects.Add(new AbilityEffect
            {
                Type = AbilityEffectType.ApplyCC,
                CCType = cc,
                Duration = TimeSpan.FromSeconds(durationSeconds)
            });
            return this;
        }

        public AbilityDefinition WithStack(StackType stack, int count = 1, double durationSeconds = 15)
        {
            Effects.Add(new AbilityEffect
            {
                Type = AbilityEffectType.ApplyStack,
                StackType = stack,
                StackCount = count,
                Duration = TimeSpan.FromSeconds(durationSeconds)
            });
            return this;
        }

        public AbilityDefinition GeneratesResource(ResourceType type, int amount)
        {
            ResourceGeneration[type] = amount;
            return this;
        }

        public AbilityDefinition WithAnimation(int animId, int soundId = 0)
        {
            CastAnimation = animId;
            CastSound = soundId;
            return this;
        }

        public AbilityDefinition WithImpactEffect(int effectId, int soundId = 0, int hue = 0)
        {
            ImpactEffectId = effectId;
            ImpactSound = soundId;
            ImpactEffectHue = hue;
            return this;
        }

        #endregion

        #region Validation

        public bool IsValid(out string error)
        {
            if (Id <= 0)
            {
                error = "Invalid ability ID";
                return false;
            }

            if (string.IsNullOrEmpty(Name))
            {
                error = "Missing ability name";
                return false;
            }

            if (Effects.Count == 0 && !IsPassive)
            {
                error = "Ability has no effects";
                return false;
            }

            error = null;
            return true;
        }

        #endregion

        #region Static Factory Methods

        /// <summary>
        /// Create a simple damage spell with automatic cost/cooldown/cast time scaling
        /// </summary>
        public static AbilityDefinition CreateDamageSpell(int id, string name, AbilitySchool school, int circle,
            int minDmg, int maxDmg, VystiaDamageType dmgType, int manaCost = 0)
        {
            // Use provided manaCost or auto-scale based on circle
            int cost = manaCost > 0 ? manaCost : AbilityCostScaling.GetManaCost(circle);
            var cooldown = AbilityCostScaling.GetCooldown(circle);
            var castTime = AbilityCostScaling.GetCastTime(circle);

            var ability = new AbilityDefinition()
                .WithId(id)
                .WithName(name)
                .InSchool(school)
                .InCircle(circle)
                .WithManaCost(cost)
                .WithCooldown(cooldown.TotalSeconds)
                .Targeting(AbilityTargetType.SingleTarget)
                .WithDamage(minDmg, maxDmg, dmgType);

            if (castTime.TotalSeconds > 0)
                ability.WithCastTime(castTime.TotalSeconds);
            else
                ability.AsInstant();

            return ability;
        }

        /// <summary>
        /// Create a simple heal spell with automatic cost/cooldown/cast time scaling
        /// </summary>
        public static AbilityDefinition CreateHealSpell(int id, string name, AbilitySchool school, int circle,
            int minHeal, int maxHeal, int manaCost = 0)
        {
            int cost = manaCost > 0 ? manaCost : AbilityCostScaling.GetManaCost(circle);
            var cooldown = AbilityCostScaling.GetCooldown(circle);
            var castTime = AbilityCostScaling.GetCastTime(circle);

            var ability = new AbilityDefinition()
                .WithId(id)
                .WithName(name)
                .InSchool(school)
                .InCircle(circle)
                .WithManaCost(cost)
                .WithCooldown(cooldown.TotalSeconds)
                .Targeting(AbilityTargetType.SingleFriendly)
                .WithHeal(minHeal, maxHeal);

            if (castTime.TotalSeconds > 0)
                ability.WithCastTime(castTime.TotalSeconds);
            else
                ability.AsInstant();

            return ability;
        }

        /// <summary>
        /// Create a DoT spell with automatic cost/cooldown/cast time scaling
        /// </summary>
        public static AbilityDefinition CreateDoTSpell(int id, string name, AbilitySchool school, int circle,
            int damagePerTick, double durationSeconds, VystiaDamageType dmgType, int manaCost = 0)
        {
            int cost = manaCost > 0 ? manaCost : AbilityCostScaling.GetManaCost(circle);
            var cooldown = AbilityCostScaling.GetCooldown(circle);
            var castTime = AbilityCostScaling.GetCastTime(circle);

            var ability = new AbilityDefinition()
                .WithId(id)
                .WithName(name)
                .InSchool(school)
                .InCircle(circle)
                .WithManaCost(cost)
                .WithCooldown(cooldown.TotalSeconds)
                .Targeting(AbilityTargetType.SingleTarget)
                .WithDoT(damagePerTick, durationSeconds, dmgType);

            if (castTime.TotalSeconds > 0)
                ability.WithCastTime(castTime.TotalSeconds);
            else
                ability.AsInstant();

            return ability;
        }

        /// <summary>
        /// Create an AoE damage spell with automatic cost/cooldown/cast time scaling
        /// </summary>
        public static AbilityDefinition CreateAoESpell(int id, string name, AbilitySchool school, int circle,
            int minDmg, int maxDmg, VystiaDamageType dmgType, int radius, int manaCost = 0)
        {
            int cost = manaCost > 0 ? manaCost : AbilityCostScaling.GetManaCost(circle);
            var cooldown = AbilityCostScaling.GetCooldown(circle);
            var castTime = AbilityCostScaling.GetCastTime(circle);

            var ability = new AbilityDefinition()
                .WithId(id)
                .WithName(name)
                .InSchool(school)
                .InCircle(circle)
                .WithManaCost(cost)
                .WithCooldown(cooldown.TotalSeconds)
                .Targeting(AbilityTargetType.TargetAoE)
                .WithAoE(radius)
                .WithDamage(minDmg, maxDmg, dmgType);

            if (castTime.TotalSeconds > 0)
                ability.WithCastTime(castTime.TotalSeconds);
            else
                ability.AsInstant();

            return ability;
        }

        /// <summary>
        /// Create a buff spell with automatic cost/cooldown/cast time scaling
        /// </summary>
        public static AbilityDefinition CreateBuffSpell(int id, string name, AbilitySchool school, int circle,
            VystiaBuffType buff, int value, double durationSeconds, int manaCost = 0)
        {
            int cost = manaCost > 0 ? manaCost : AbilityCostScaling.GetManaCost(circle);
            var cooldown = AbilityCostScaling.GetCooldown(circle);
            var castTime = AbilityCostScaling.GetCastTime(circle);

            var ability = new AbilityDefinition()
                .WithId(id)
                .WithName(name)
                .InSchool(school)
                .InCircle(circle)
                .WithManaCost(cost)
                .WithCooldown(cooldown.TotalSeconds)
                .Targeting(AbilityTargetType.SingleFriendly)
                .WithBuff(buff, durationSeconds, value);

            if (castTime.TotalSeconds > 0)
                ability.WithCastTime(castTime.TotalSeconds);
            else
                ability.AsInstant();

            return ability;
        }

        /// <summary>
        /// Create a martial strike with automatic stamina cost scaling
        /// </summary>
        public static AbilityDefinition CreateMartialStrike(int id, string name, AbilitySchool school,
            int minDmg, int maxDmg, int staminaCost = 0, int tier = 1)
        {
            int cost = staminaCost > 0 ? staminaCost : AbilityCostScaling.GetStaminaCost(tier);

            return new AbilityDefinition()
                .WithId(id)
                .WithName(name)
                .InSchool(school)
                .InCircle(tier) // Martial tier maps to circle
                .WithStaminaCost(cost)
                .WithCooldown(tier * 1.5) // Basic cooldown scaling for martial
                .Targeting(AbilityTargetType.SingleTarget, 2)
                .AsInstant()
                .WithDamage(minDmg, maxDmg, VystiaDamageType.Physical);
        }

        /// <summary>
        /// Create a finisher that consumes combo points with automatic stamina cost scaling
        /// </summary>
        public static AbilityDefinition CreateFinisher(int id, string name, AbilitySchool school,
            int baseDmg, int dmgPerStack, int staminaCost = 0, int tier = 3)
        {
            int cost = staminaCost > 0 ? staminaCost : AbilityCostScaling.GetStaminaCost(tier);

            var ability = new AbilityDefinition()
                .WithId(id)
                .WithName(name)
                .InSchool(school)
                .InCircle(tier)
                .WithStaminaCost(cost)
                .WithCooldown(6.0) // Finishers have fixed 6 second cooldown
                .Targeting(AbilityTargetType.SingleTarget, 2)
                .AsInstant()
                .AsFinisher();

            // Base damage plus bonus per consumed stack
            ability.Effects.Add(new AbilityEffect
            {
                Type = AbilityEffectType.DirectDamage,
                MinValue = baseDmg,
                MaxValue = baseDmg,
                DamageType = VystiaDamageType.Physical
            });

            ability.Effects.Add(new AbilityEffect
            {
                Type = AbilityEffectType.ConsumeStack,
                StackType = StackType.Combo
            });

            return ability;
        }

        #endregion
    }

    #endregion
}
